# Site settings
title: Alan's Profile
email: www.alan-17@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome!
baseurl: "artorres7"
url: "http://artorres7.github.io"
twitter_username: artorres7
github_username:  artorres7
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
